name: FarmData2 Pull Request
on:
  pull_request:
    branches:
    - main
    types: [opened, edited, synchronize]

jobs:
  Must-Check-DCO-Statement:
    runs-on: ubuntu-latest
    steps:
    - name: Tack Completed Checker
      uses: kentaro-m/task-completed-checker-action@v0.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"  
        
  Code-Must-Be-Formatted-By-Prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Commit
      uses: actions/checkout@v2
      with:
       # Make sure the actual branch is checked out when running on pull requests
       ref: ${{ github.head_ref }}
       # This is important to fetch the changes to the previous commit
       fetch-depth: 0
    - name: Run Prettier
      uses: creyD/prettier_action@v3.1
      with:
        prettier_options: **/*.{js,html,css,md}
        only_changed: true
        dry: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
