name: FarmData2 Pull Request
on:
  pull_request:
    branches:
    - main
    types: [opened, edited]

jobs:
  DCO-must-be-checked:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}":

  Prettier-must-be-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Commit
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
        # This is important to fetch the changes to the previous commit
        fetch-depth: 0
    - name: Run Prettier
      uses: creyD/prettier_action@v3.1
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{php,html,js,md}
        only_changed: True
        dry: True
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
