name: Check DCO
on:
  pull_request:
    branches:
      - main   
jobs:
  check-dco-box:
    runs-on: ubuntu-latest
    steps:
      - uses: WeeverApps/gha-task-list-zero@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
